version: "3.9"
services:
  app:
    build: .
    #image: docker.pl/app
    restart: always
    container_name: app
    hostname: app
    ports:
      - "80:80"
    volumes:
      - ./docker/app/:/var/www/html/var/
    environment:
      APP_ENV: dev
      APP_SECRET: 1234567890qwertyuiop
      DATABASE_URL: postgresql://postgres:LwcaqNJtSSaDRPmDYrVW@db:5432/shelter
    networks:
      - local
      - nginx
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: LwcaqNJtSSaDRPmDYrVW
      POSTGRES_DB: shelter
    volumes:
      - ./docker/db/:/var/lib/postgresql/data
    networks:
      - local

networks:
  local:
    external: false
  nginx:
    external: true
